import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const cliPath = path.join(repositoryRoot, "dist", "cli.js");

function runCli(root: string, command: "check" | "sync", ...args: string[]): string {
  return execFileSync(process.execPath, [cliPath, command, "--root", root, ...args], {
    cwd: repositoryRoot,
    encoding: "utf8",
  });
}

test("CLIはshared configのnamingと明示Project scopeをそのまま使う", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "bem-modules-cli-"));
  try {
    await fs.mkdir(path.join(root, "src"));
    await fs.writeFile(
      path.join(root, "bem-modules.config.mjs"),
      [
        "export default {",
        '  naming: { wordCase: "kebab" },',
        '  project: { include: ["src"] },',
        "  types: true,",
        "};",
        "",
      ].join("\n"),
      "utf8",
    );
    await fs.writeFile(
      path.join(root, "src", "Card.module.css"),
      "/* @block p-card */ .root {} .profile-image {} .profile-image--rounded {}\n",
      "utf8",
    );
    // This duplicate is outside the configured scope. If the CLI ignored the
    // shared project.include, check would incorrectly report BEM003.
    await fs.writeFile(
      path.join(root, "Ignored.module.css"),
      "/* @block p-card */ .root {}\n",
      "utf8",
    );

    assert.match(runCli(root, "check"), /^check: 1 BEM CSS Module\(s\)\n$/);
    assert.match(runCli(root, "sync"), /^sync: 1 BEM CSS Module\(s\)\n$/);
    const dts = await fs.readFile(path.join(root, "src", "Card.module.css.d.ts"), "utf8");
    assert.match(dts, /readonly "profileImageRounded": string/);
    await assert.rejects(() => fs.access(path.join(root, "Ignored.module.css.d.ts")), { code: "ENOENT" });
  } finally {
    await fs.rm(root, { recursive: true, force: true });
  }
});

test("CLI syncは隣接型のsymlinkを生成時に拒否し、掃除でも参照先に触れない", async () => {
  const parent = await fs.mkdtemp(path.join(os.tmpdir(), "bem-modules-cli-link-"));
  try {
    const root = path.join(parent, "app");
    await fs.mkdir(root);
    const source = path.join(root, "Card.module.css");
    const target = path.join(parent, "External.module.css.d.ts");
    const original = "// Generated by vite-plugin-bem-modules. Do not edit.\nexport const external = true;\n";
    await fs.writeFile(source, "/* @block card */ .root {}");
    await fs.writeFile(target, original);
    await fs.symlink(target, `${source}.d.ts`, "file");
    assert.throws(() => runCli(root, "sync"), /BEM006/);
    assert.equal(await fs.readFile(target, "utf8"), original);

    await fs.writeFile(source, ".root {}");
    assert.match(runCli(root, "sync", "--include", "Card.module.css"), /sync: 0/);
    assert.equal(await fs.readFile(target, "utf8"), original);
    assert.ok((await fs.lstat(`${source}.d.ts`)).isSymbolicLink());

    await fs.unlink(source);
    runCli(root, "sync", "--include", "Card.module.css");
    assert.equal(await fs.readFile(target, "utf8"), original);
    assert.ok((await fs.lstat(`${source}.d.ts`)).isSymbolicLink());

    await fs.writeFile(source, "/* @block card */ .root {}");
    await fs.unlink(target);
    assert.throws(() => runCli(root, "sync"), /BEM006/);
    await assert.rejects(() => fs.access(target), { code: "ENOENT" });
    assert.ok((await fs.lstat(`${source}.d.ts`)).isSymbolicLink());
  } finally {
    await fs.rm(parent, { recursive: true, force: true });
  }
});

test("CLI syncは疑問符を含む実ファイルの隣へ型を生成する", {
  skip: process.platform === "win32" ? "Windowsのファイル名には疑問符を使用できない" : false,
}, async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "bem-modules-cli-question-"));
  try {
    const name = "Question?.module.css";
    await fs.writeFile(path.join(root, name), "/* @block card */ .root {}");
    runCli(root, "sync");
    assert.match(await fs.readFile(path.join(root, `${name}.d.ts`), "utf8"), /readonly "root": string/);
    assert.deepEqual((await fs.readdir(root)).sort(), [name, `${name}.d.ts`].sort());
  } finally {
    await fs.rm(root, { recursive: true, force: true });
  }
});
