import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { createServer } from "vite";
import test from "node:test";
import bemModules, { createBemPostcssPlugin } from "vite-plugin-bem-modules";

function testBemModules(options: Parameters<typeof bemModules>[0] = {}) {
  const plugins = bemModules(options);
  assert.ok(Array.isArray(plugins));
  const postcssPlugin = createBemPostcssPlugin();
  return [
    ...plugins,
    {
      name: "test-register-bem-postcss",
      config: () => ({ css: { postcss: { plugins: [postcssPlugin] } } }),
    },
  ];
}

function cssSource(modifier: string): string {
  return [
    "/* @block p-card */",
    ".root { color: red; }",
    `.root--${modifier} { gap: 4px; }`,
    "",
  ].join("\n");
}

async function waitFor(predicate: () => Promise<boolean>, timeoutMs = 5_000): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (await predicate()) return;
    await new Promise((resolve) => setTimeout(resolve, 50));
  }
  throw new Error(`timed out after ${timeoutMs}ms`);
}

async function closeServerAndRemoveRoot(
  server: Awaited<ReturnType<typeof createServer>> | null,
  root: string,
): Promise<void> {
  try {
    if (server) await server.close();
  } finally {
    await fs.rm(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 50 });
  }
}

function generatedDts(className: string): string {
  return [
    "// Generated by vite-plugin-bem-modules. Do not edit.",
    "export type Styles = {",
    `  readonly ${JSON.stringify(className)}: string;`,
    "};",
    "",
    "declare const styles: Styles;",
    "",
    "export default styles;",
    "",
  ].join("\n");
}

test("Vite dev serverは未importModuleを自動同期せず、処理時にd.tsを生成する", async () => {
  // Vite's Windows request resolver can shorten the user temp path (RUNNER~1)
  // while the fixture was created through its long form. Keep this fixture on
  // the checkout drive so the request and file-system paths agree.
  const fixtureParent = process.platform === "win32" ? process.cwd() : os.tmpdir();
  const root = await fs.mkdtemp(path.join(fixtureParent, "bem-modules-dev-reconcile-"));
  const cardCssFile = path.join(root, "Card.module.css");
  const buttonCssFile = path.join(root, "Button.module.css");
  const cardDtsFile = `${cardCssFile}.d.ts`;
  const buttonDtsFile = `${buttonCssFile}.d.ts`;
  let server: Awaited<ReturnType<typeof createServer>> | null = null;

  try {
    await fs.writeFile(cardCssFile, "/* @block p-card */ .root {} .root--compact {}\n", "utf8");
    await fs.writeFile(buttonCssFile, "/* @block p-button */ .root {} .root--large {}\n", "utf8");
    await fs.writeFile(cardDtsFile, generatedDts("staleCard"), "utf8");
    await fs.writeFile(buttonDtsFile, generatedDts("staleButton"), "utf8");

    server = await createServer({
      root,
      configFile: false,
      logLevel: "silent",
      plugins: [testBemModules()],
      server: { middlewareMode: true, watch: null },
    });

    assert.match(await fs.readFile(cardDtsFile, "utf8"), /"staleCard"/);
    assert.match(await fs.readFile(buttonDtsFile, "utf8"), /"staleButton"/);
    await server.transformRequest("/Card.module.css");
    await server.transformRequest("/Button.module.css");
    const cardDts = await fs.readFile(cardDtsFile, "utf8");
    const buttonDts = await fs.readFile(buttonDtsFile, "utf8");
    assert.match(cardDts, /"root"/);
    assert.doesNotMatch(cardDts, /"staleCard"/);
    assert.match(buttonDts, /"root"/);
    assert.doesNotMatch(buttonDts, /"staleButton"/);
  } finally {
    await closeServerAndRemoveRoot(server, root);
  }
});

test("実Vite dev serverでCSS変更をProjectとflat API・d.tsへ同期する", {
  skip: process.platform === "win32"
    ? "Viteの実watcherはWindows runnerのlibuv assertionを避け、hotUpdate境界を別testで検証する"
    : false,
}, async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "bem-modules-dev-"));
  const cssFile = path.join(root, "Card.module.css");
  const mainFile = path.join(root, "main.ts");
  const dtsFile = `${cssFile}.d.ts`;
  let server: Awaited<ReturnType<typeof createServer>> | null = null;

  try {
    await fs.writeFile(cssFile, cssSource("compact"), "utf8");
    await fs.writeFile(
      mainFile,
      "import styles from './Card.module.css';\nexport const value = styles.rootCompact;\n",
      "utf8",
    );

    server = await createServer({
      root,
      configFile: false,
      logLevel: "silent",
      plugins: [testBemModules()],
      server: {
        middlewareMode: true,
      },
    });

    const initial = await server.transformRequest("/main.ts");
    assert.match(initial?.code ?? "", /rootCompact/);
    await server.transformRequest("/Card.module.css");
    assert.match(await fs.readFile(dtsFile, "utf8"), /"rootCompact"/);

    await fs.writeFile(cssFile, cssSource("large"), "utf8");
    // The adapter lets Vite/PostCSS own updates; it must not read or compile
    // the changed source itself.
    const cssPlugin = server.config.plugins.find(
      (plugin) => plugin.name === "vite-plugin-bem-modules:css",
    );
    assert.ok(cssPlugin?.hotUpdate);
    const hotUpdate = typeof cssPlugin.hotUpdate === "function"
      ? cssPlugin.hotUpdate
      : cssPlugin.hotUpdate.handler;
    const hotUpdateResult = await hotUpdate.call(
      { warn() {} } as never,
      {
        type: "update",
        file: cssFile,
        timestamp: Date.now(),
        modules: [],
        read: async () => { throw new Error("hotUpdate must not read source"); },
        server,
      } as never,
    );
    assert.equal(hotUpdateResult, undefined);
    const unchangedDts = await fs.readFile(dtsFile, "utf8");
    assert.match(unchangedDts, /"rootCompact"/);
    assert.doesNotMatch(unchangedDts, /"rootLarge"/);
  } finally {
    await closeServerAndRemoveRoot(server, root);
  }
});

test("Viteの並行リクエストでも同名Blockを許容し、各Moduleを処理する", async () => {
  const fixtureParent = process.platform === "win32" ? process.cwd() : os.tmpdir();
  const root = await fs.mkdtemp(path.join(fixtureParent, "bem-modules-dev-concurrent-"));
  let server: Awaited<ReturnType<typeof createServer>> | null = null;
  try {
    const names = Array.from({ length: 8 }, (_, index) => `Card${index}.module.css`);
    for (const name of names) {
      await fs.writeFile(path.join(root, name), ".plain { color: red; }", "utf8");
    }
    server = await createServer({
      root,
      configFile: false,
      logLevel: "silent",
      plugins: [testBemModules()],
      server: { middlewareMode: true, watch: null },
    });
    // Keep the files present during startup so Vite does not cache a missing
    // filesystem result on Windows, then make them BEM-owned after the initial
    // Project scan so concurrent requests exercise the incremental path.
    for (const name of names) {
      await fs.writeFile(path.join(root, name), "/* @block p-card */ .root { color: red; }", "utf8");
    }
    const activeServer = server;
    const results = await Promise.allSettled(names.map((name) => activeServer.transformRequest(`/${name}`)));
    const failures = results.filter((result) => result.status === "rejected");
    assert.deepEqual(failures.map((result) => String(result.reason)), []);
    assert.equal(results.filter((result) => result.status === "fulfilled").length, names.length);
    for (const [index, result] of results.entries()) {
      const dtsFile = path.join(root, `${names[index]}.d.ts`);
      if (result.status === "fulfilled") {
        assert.match(result.value?.code ?? "", /p-card/);
        assert.match(await fs.readFile(dtsFile, "utf8"), /readonly "root": string/);
      }
    }
    const generatedTypes = await Promise.all(names.map(async (name) => {
      try {
        await fs.access(path.join(root, `${name}.d.ts`));
        return name;
      } catch {
        return null;
      }
    }));
    assert.equal(generatedTypes.filter((name) => name !== null).length, names.length);
    await fs.writeFile(path.join(root, "Button.module.css"), "/* @block p-button */ .root { color: blue; }", "utf8");
    assert.match((await server.transformRequest("/Button.module.css"))?.code ?? "", /p-button/);
  } finally {
    await closeServerAndRemoveRoot(server, root);
  }
});

test("Vite dev serverはd.ts同期失敗時にschemaを公開しない", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "bem-modules-dev-dts-order-"));
  const cssFile = path.join(root, "Card.module.css");
  const dtsFile = `${cssFile}.d.ts`;
  let server: Awaited<ReturnType<typeof createServer>> | null = null;

  try {
    await fs.writeFile(cssFile, "/* @block p-card */ .root {}\n", "utf8");
    await fs.writeFile(dtsFile, "export default {} as Record<string, string>;\n", "utf8");
    server = await createServer({
      root,
      configFile: false,
      logLevel: "silent",
      plugins: [testBemModules()],
      server: { middlewareMode: true, watch: null },
    });
    await assert.rejects(
      () => server!.transformRequest("/Card.module.css"),
      /vite-plugin-bem-modules:BEM006/,
    );
    await fs.rm(dtsFile);
    const transformed = await server.transformRequest("/Card.module.css");
    assert.match(transformed?.code ?? "", /p-card/);
    assert.match(await fs.readFile(dtsFile, "utf8"), /readonly "root": string/);
  } finally {
    await closeServerAndRemoveRoot(server, root);
  }
});

test("Vite dev serverはHMRで同名Blockを許容し、生成d.tsを更新する", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "bem-modules-dev-analysis-error-"));
  const aFile = path.join(root, "A.module.css");
  const bFile = path.join(root, "B.module.css");
  const mainFile = path.join(root, "main.ts");
  const bDtsFile = `${bFile}.d.ts`;
  let server: Awaited<ReturnType<typeof createServer>> | null = null;

  try {
    await fs.writeFile(aFile, "/* @block shared */ .root {}\n", "utf8");
    await fs.writeFile(bFile, "/* @block other */ .root {}\n", "utf8");
    await fs.writeFile(
      mainFile,
      "import './A.module.css';\nimport styles from './B.module.css';\nexport const value = styles.root;\n",
      "utf8",
    );

    server = await createServer({
      root,
      configFile: false,
      logLevel: "silent",
      plugins: [testBemModules()],
      server: { middlewareMode: true, watch: null },
    });

    await server.transformRequest("/main.ts");
    await server.transformRequest("/B.module.css");
    assert.match(await fs.readFile(bDtsFile, "utf8"), /readonly "root": string/);

    await fs.writeFile(bFile, "/* @block shared */ .root {}\n", "utf8");
    const cssPlugin = server.config.plugins.find(
      (plugin) => plugin.name === "vite-plugin-bem-modules:css",
    );
    assert.ok(cssPlugin?.hotUpdate);
    const hotUpdate = typeof cssPlugin.hotUpdate === "function"
      ? cssPlugin.hotUpdate
      : cssPlugin.hotUpdate.handler;
    const hotUpdateResult = await hotUpdate.call(
        { warn() {} } as never,
        {
          type: "update",
          file: bFile,
          timestamp: Date.now(),
          modules: [],
          read: async () => { throw new Error("hotUpdate must not read source"); },
          server,
        } as never,
      );
    assert.equal(hotUpdateResult, undefined);
    await server.transformRequest(`/B.module.css?direct=${Date.now()}`);
    assert.match(await fs.readFile(bDtsFile, "utf8"), /readonly "root": string/);
  } finally {
    await closeServerAndRemoveRoot(server, root);
  }
});

test("HMR updateはViteとPostCSSへ委譲し、失敗後の次の変換を妨げない", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "bem-modules-dev-hmr-recovery-"));
  const cssFile = path.join(root, "Card.module.css");
  let server: Awaited<ReturnType<typeof createServer>> | null = null;
  try {
    await fs.writeFile(cssFile, cssSource("compact"), "utf8");
    server = await createServer({
      root,
      configFile: false,
      logLevel: "silent",
      plugins: [testBemModules()],
      server: { middlewareMode: true, watch: null },
    });
    await server.transformRequest("/Card.module.css");
    const cssPlugin = server.config.plugins.find((plugin) => plugin.name === "vite-plugin-bem-modules:css");
    assert.ok(cssPlugin?.hotUpdate);
    const hotUpdate = typeof cssPlugin.hotUpdate === "function" ? cssPlugin.hotUpdate : cssPlugin.hotUpdate.handler;
    const result = await hotUpdate.call(
      { warn() {} } as never,
      {
        type: "update",
        file: cssFile,
        timestamp: Date.now(),
        modules: [],
        read: async () => { throw new Error("hotUpdate must not read source"); },
        server,
      } as never,
    );
    assert.equal(result, undefined);

    const dts = await fs.readFile(`${cssFile}.d.ts`, "utf8");
    assert.match(dts, /readonly "rootCompact": string/);
    assert.doesNotMatch(dts, /rootLarge|rootInvalid/);

    await fs.writeFile(path.join(root, "Other.module.css"), cssSource("compact"), "utf8");
    const activeServer = server;
    await assert.doesNotReject(() => activeServer.transformRequest("/Other.module.css"));
  } finally {
    await closeServerAndRemoveRoot(server, root);
  }
});

test("Vite Adapterはimporter変更だけでProject stateを変更しない", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "bem-modules-dev-importer-"));
  const aFile = path.join(root, "A.module.css");
  const bFile = path.join(root, "B.module.css");
  const mainFile = path.join(root, "main.ts");
  let server: Awaited<ReturnType<typeof createServer>> | null = null;

  try {
    await fs.writeFile(aFile, "/* @block p-a */ .root {}", "utf8");
    await fs.writeFile(bFile, "/* @block p-b */ .root {}", "utf8");
    await fs.writeFile(mainFile, "import styles from './A.module.css';\nexport const value = styles.root;\n", "utf8");

    server = await createServer({
      root,
      configFile: false,
      logLevel: "silent",
      plugins: [testBemModules({ types: false })],
      server: {
        middlewareMode: true,
        watch: null,
      },
    });
    await server.transformRequest("/main.ts");
    await server.transformRequest("/A.module.css");

    await fs.writeFile(mainFile, "import styles from './B.module.css';\nexport const value = styles.root;\n", "utf8");
    const plugins = server.config.plugins;
    const cssPlugin = plugins.find((plugin) => plugin.name === "vite-plugin-bem-modules:css");
    assert.ok(cssPlugin?.hotUpdate);
    const result = await (typeof cssPlugin.hotUpdate === "function" ? cssPlugin.hotUpdate : cssPlugin.hotUpdate.handler).call(
      { warn() {} } as never,
      {
        type: "update",
        file: mainFile,
        timestamp: Date.now(),
        modules: [],
        read: async () => await fs.readFile(mainFile, "utf8"),
        server,
      } as never,
    );
    assert.equal(result, undefined);
  } finally {
    await closeServerAndRemoveRoot(server, root);
  }
});

test("Vite dev serverはroot外の明示includeをwatcherへ登録し、変更をd.tsへ同期する", {
  skip: process.platform === "win32"
    ? "Viteの実watcherはWindows runnerのlibuv assertionを避ける"
    : false,
}, async () => {
  const parent = await fs.mkdtemp(path.join(os.tmpdir(), "bem-modules-dev-external-watch-"));
  const root = path.join(parent, "app");
  const external = path.join(parent, "shared");
  const cssFile = path.join(external, "Shared.module.css");
  const dtsFile = `${cssFile}.d.ts`;
  let server: Awaited<ReturnType<typeof createServer>> | null = null;

  try {
    await fs.mkdir(root);
    await fs.mkdir(external);
    await fs.writeFile(cssFile, cssSource("compact"), "utf8");
    await fs.writeFile(
      path.join(root, "main.ts"),
      "import styles from '../shared/Shared.module.css'; export const value = styles.root;\n",
      "utf8",
    );

    server = await createServer({
      root,
      configFile: false,
      logLevel: "silent",
      plugins: [testBemModules({ types: true, project: { include: [".", external] } })],
      server: {
        middlewareMode: true,
        watch: { usePolling: true, interval: 50 },
      },
    });
    await server.transformRequest("/main.ts");

    await waitFor(async () => {
      try {
        return (await fs.readFile(dtsFile, "utf8")).includes('"rootCompact"');
      } catch {
        return false;
      }
    });

    await fs.writeFile(cssFile, cssSource("large"), "utf8");
    const cssPlugin = server.config.plugins.find(
      (plugin) => plugin.name === "vite-plugin-bem-modules:css",
    );
    assert.ok(cssPlugin?.hotUpdate);
    const hotUpdate = typeof cssPlugin.hotUpdate === "function"
      ? cssPlugin.hotUpdate
      : cssPlugin.hotUpdate.handler;
    const hotUpdateResult = await hotUpdate.call(
      { warn() {} } as never,
      {
        type: "update",
        file: cssFile,
        timestamp: Date.now(),
        modules: [],
        read: async () => { throw new Error("hotUpdate must not read source"); },
        server,
      } as never,
    );
    assert.equal(hotUpdateResult, undefined);
    const unchangedDts = await fs.readFile(dtsFile, "utf8");
    assert.match(unchangedDts, /"rootCompact"/);
    assert.doesNotMatch(unchangedDts, /"rootLarge"/);
  } finally {
    await closeServerAndRemoveRoot(server, parent);
  }
});

test("HMRは非class exportのprojection変更でもVite標準の更新へ委譲する", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "bem-modules-dev-nonclass-hmr-"));
  const cssFile = path.join(root, "Card.module.css");
  const mainFile = path.join(root, "main.ts");
  let server: Awaited<ReturnType<typeof createServer>> | null = null;

  try {
    await fs.writeFile(
      cssFile,
      "/* @block p-card */ @keyframes fade { from { opacity: 0; } to { opacity: 1; } } .root {}",
      "utf8",
    );
    await fs.writeFile(
      mainFile,
      "import styles from './Card.module.css'; export const value = styles.root;\n",
      "utf8",
    );
    server = await createServer({
      root,
      configFile: false,
      logLevel: "silent",
      plugins: [testBemModules({ types: false })],
      server: { middlewareMode: true, watch: null },
    });
    await server.transformRequest("/Card.module.css");

    const mainNode = { file: mainFile, id: mainFile, importers: new Set() };
    const cssNode = { file: cssFile, id: cssFile, importers: new Set([mainNode]) };
    const cssPlugin = server.config.plugins.find((plugin) => plugin.name === "vite-plugin-bem-modules:css");
    assert.ok(cssPlugin?.hotUpdate);
    const hotUpdate = typeof cssPlugin.hotUpdate === "function"
      ? cssPlugin.hotUpdate
      : cssPlugin.hotUpdate.handler;
    const result = await hotUpdate.call(
      { warn() {} } as never,
      {
        type: "update",
        file: cssFile,
        timestamp: Date.now(),
        modules: [cssNode],
        read: async () => "/* @block p-card */ @keyframes fade-next { from { opacity: 0; } to { opacity: 1; } } .root {}",
        server,
      } as never,
    );
    assert.equal(result, undefined);
  } finally {
    await closeServerAndRemoveRoot(server, root);
  }
});
