import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { createServer } from "vite";
import test from "node:test";
import bemModules from "vite-plugin-bem-modules";

function cssSource(modifier: string): string {
  return [
    "/* @block p-card */",
    ".root { color: red; }",
    `.root--${modifier} { gap: 4px; }`,
    "",
  ].join("\n");
}

async function waitFor(predicate: () => Promise<boolean>, timeoutMs = 5_000): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (await predicate()) return;
    await new Promise((resolve) => setTimeout(resolve, 50));
  }
  throw new Error(`timed out after ${timeoutMs}ms`);
}

async function closeServerAndRemoveRoot(
  server: Awaited<ReturnType<typeof createServer>> | null,
  root: string,
): Promise<void> {
  try {
    if (server) await server.close();
  } finally {
    await fs.rm(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 50 });
  }
}

function generatedDts(className: string): string {
  return [
    "// Generated by vite-plugin-bem-modules. Do not edit.",
    "export type Styles = {",
    `  readonly ${JSON.stringify(className)}: string;`,
    "};",
    "",
    "declare const styles: Styles;",
    "",
    "export default styles;",
    "",
  ].join("\n");
}

test("Vite dev serverはserve開始時に未importのProject scopeも生成d.tsへ同期する", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "bem-modules-dev-reconcile-"));
  const cardCssFile = path.join(root, "Card.module.css");
  const buttonCssFile = path.join(root, "Button.module.css");
  const cardDtsFile = `${cardCssFile}.d.ts`;
  const buttonDtsFile = `${buttonCssFile}.d.ts`;
  let server: Awaited<ReturnType<typeof createServer>> | null = null;

  try {
    await fs.writeFile(cardCssFile, "/* @block p-card */ .root {} .root--compact {}\n", "utf8");
    await fs.writeFile(buttonCssFile, "/* @block p-button */ .root {} .root--large {}\n", "utf8");
    await fs.writeFile(cardDtsFile, generatedDts("staleCard"), "utf8");
    await fs.writeFile(buttonDtsFile, generatedDts("staleButton"), "utf8");

    server = await createServer({
      root,
      configFile: false,
      logLevel: "silent",
      plugins: [bemModules()],
      server: { middlewareMode: true, watch: null },
    });

    const cardDts = await fs.readFile(cardDtsFile, "utf8");
    const buttonDts = await fs.readFile(buttonDtsFile, "utf8");
    assert.match(cardDts, /"rootCompact"/);
    assert.doesNotMatch(cardDts, /"staleCard"/);
    assert.match(buttonDts, /"rootLarge"/);
    assert.doesNotMatch(buttonDts, /"staleButton"/);
  } finally {
    await closeServerAndRemoveRoot(server, root);
  }
});

test("実Vite dev serverでCSS変更をProjectとflat API・d.tsへ同期する", {
  skip: process.platform === "win32"
    ? "Viteの実watcherはWindows runnerのlibuv assertionを避け、hotUpdate境界を別testで検証する"
    : false,
}, async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "bem-modules-dev-"));
  const cssFile = path.join(root, "Card.module.css");
  const mainFile = path.join(root, "main.ts");
  const dtsFile = `${cssFile}.d.ts`;
  let server: Awaited<ReturnType<typeof createServer>> | null = null;

  try {
    await fs.writeFile(cssFile, cssSource("compact"), "utf8");
    await fs.writeFile(
      mainFile,
      "import styles from './Card.module.css';\nexport const value = styles.rootCompact;\n",
      "utf8",
    );

    server = await createServer({
      root,
      configFile: false,
      logLevel: "silent",
      plugins: [bemModules()],
      server: {
        middlewareMode: true,
      },
    });

    const initial = await server.transformRequest("/main.ts");
    assert.match(initial?.code ?? "", /rootCompact/);
    await server.transformRequest("/Card.module.css");
    assert.match(await fs.readFile(dtsFile, "utf8"), /"rootCompact"/);

    await fs.writeFile(cssFile, cssSource("large"), "utf8");
    // Keep one production-path check: chokidar event -> Vite hotUpdate ->
    // Project compile -> d.ts projection.
    server.watcher.emit("change", path.join(server.config.root, "Card.module.css"));
    await waitFor(async () => {
      try {
        const dts = await fs.readFile(dtsFile, "utf8");
        return dts.includes('"rootLarge"') && !dts.includes('"rootCompact"');
      } catch {
        return false;
      }
    });
    assert.match(await fs.readFile(dtsFile, "utf8"), /"rootLarge"/);
    assert.doesNotMatch(await fs.readFile(dtsFile, "utf8"), /"rootCompact"/);
    const updatedCss = await server.transformRequest("/Card.module.css");
    assert.match(updatedCss?.code ?? "", /p-card--large/);
    assert.doesNotMatch(updatedCss?.code ?? "", /p-card--compact/);
  } finally {
    await closeServerAndRemoveRoot(server, root);
  }
});

test("Viteの並行リクエストでも重複Blockを拒否し、その後の正常なModuleを処理する", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "bem-modules-dev-concurrent-"));
  let server: Awaited<ReturnType<typeof createServer>> | null = null;
  try {
    const names = Array.from({ length: 8 }, (_, index) => `Card${index}.module.css`);
    for (const name of names) {
      await fs.writeFile(path.join(root, name), ".plain { color: red; }", "utf8");
    }
    server = await createServer({
      root,
      configFile: false,
      logLevel: "silent",
      plugins: [bemModules()],
      server: { middlewareMode: true, watch: null },
    });
    // Keep the files present during startup so Vite does not cache a missing
    // filesystem result on Windows, then make them BEM-owned after the initial
    // Project scan so concurrent requests exercise the incremental path.
    for (const name of names) {
      await fs.writeFile(path.join(root, name), "/* @block p-card */ .root { color: red; }", "utf8");
    }
    const activeServer = server;
    const results = await Promise.allSettled(names.map((name) => activeServer.transformRequest(`/${name}`)));
    assert.ok(results.filter((result) => result.status === "fulfilled").length <= 1);
    assert.ok(results.filter((result) => result.status === "rejected").length >= names.length - 1);
    for (const [index, result] of results.entries()) {
      const dtsFile = path.join(root, `${names[index]}.d.ts`);
      if (result.status === "rejected") {
        assert.match(String(result.reason), /vite-plugin-bem-modules:BEM003/);
      } else {
        assert.match(result.value?.code ?? "", /p-card/);
        assert.match(await fs.readFile(dtsFile, "utf8"), /readonly "root": string/);
      }
    }
    const generatedTypes = await Promise.all(names.map(async (name) => {
      try {
        await fs.access(path.join(root, `${name}.d.ts`));
        return name;
      } catch {
        return null;
      }
    }));
    assert.ok(generatedTypes.filter((name) => name !== null).length <= 1);
    await fs.writeFile(path.join(root, "Button.module.css"), "/* @block p-button */ .root { color: blue; }", "utf8");
    assert.match((await server.transformRequest("/Button.module.css"))?.code ?? "", /p-button/);
  } finally {
    await closeServerAndRemoveRoot(server, root);
  }
});

test("Vite dev serverはd.ts同期失敗時にschemaを公開しない", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "bem-modules-dev-dts-order-"));
  const cssFile = path.join(root, "Card.module.css");
  const dtsFile = `${cssFile}.d.ts`;
  let server: Awaited<ReturnType<typeof createServer>> | null = null;

  try {
    await fs.writeFile(cssFile, "/* @block p-card */ .root {}\n", "utf8");
    await fs.writeFile(dtsFile, "export default {} as Record<string, string>;\n", "utf8");
    await assert.rejects(
      () => createServer({
        root,
        configFile: false,
        logLevel: "silent",
        plugins: [bemModules()],
        server: { middlewareMode: true, watch: null },
      }),
      /vite-plugin-bem-modules:BEM006/,
    );
    await fs.rm(dtsFile);
    server = await createServer({
      root,
      configFile: false,
      logLevel: "silent",
      plugins: [bemModules()],
      server: { middlewareMode: true, watch: null },
    });
    const transformed = await server.transformRequest("/Card.module.css");
    assert.match(transformed?.code ?? "", /p-card/);
    assert.match(await fs.readFile(dtsFile, "utf8"), /readonly "root": string/);
  } finally {
    await closeServerAndRemoveRoot(server, root);
  }
});

test("Vite dev serverはHMR解析失敗時に旧schemaと生成d.tsを残さない", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "bem-modules-dev-analysis-error-"));
  const aFile = path.join(root, "A.module.css");
  const bFile = path.join(root, "B.module.css");
  const mainFile = path.join(root, "main.ts");
  const bDtsFile = `${bFile}.d.ts`;
  let server: Awaited<ReturnType<typeof createServer>> | null = null;

  try {
    await fs.writeFile(aFile, "/* @block shared */ .root {}\n", "utf8");
    await fs.writeFile(bFile, "/* @block other */ .root {}\n", "utf8");
    await fs.writeFile(
      mainFile,
      "import './A.module.css';\nimport styles from './B.module.css';\nexport const value = styles.root;\n",
      "utf8",
    );

    server = await createServer({
      root,
      configFile: false,
      logLevel: "silent",
      plugins: [bemModules()],
      server: { middlewareMode: true, watch: null },
    });

    await server.transformRequest("/main.ts");
    await server.transformRequest("/B.module.css");
    assert.match(await fs.readFile(bDtsFile, "utf8"), /readonly "root": string/);

    await fs.writeFile(bFile, "/* @block shared */ .root {}\n", "utf8");
    const cssPlugin = server.config.plugins.find(
      (plugin) => plugin.name === "vite-plugin-bem-modules:css",
    );
    assert.ok(cssPlugin?.hotUpdate);
    const hotUpdate = typeof cssPlugin.hotUpdate === "function"
      ? cssPlugin.hotUpdate
      : cssPlugin.hotUpdate.handler;
    await assert.rejects(
      () => hotUpdate.call(
        { warn() {} } as never,
        {
          type: "update",
          file: bFile,
          timestamp: Date.now(),
          modules: [],
          read: async () => await fs.readFile(bFile, "utf8"),
          server,
        } as never,
      ),
      /vite-plugin-bem-modules:BEM003/,
    );
    await assert.rejects(() => fs.access(bDtsFile), { code: "ENOENT" });
  } finally {
    await closeServerAndRemoveRoot(server, root);
  }
});

test("並行HMRの失敗処理が後続の正常なschemaと生成型を削除しない", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "bem-modules-dev-hmr-recovery-"));
  const cssFile = path.join(root, "Card.module.css");
  let server: Awaited<ReturnType<typeof createServer>> | null = null;
  try {
    await fs.writeFile(cssFile, cssSource("compact"), "utf8");
    server = await createServer({
      root,
      configFile: false,
      logLevel: "silent",
      plugins: [bemModules()],
      server: { middlewareMode: true, watch: null },
    });
    const cssPlugin = server.config.plugins.find((plugin) => plugin.name === "vite-plugin-bem-modules:css");
    assert.ok(cssPlugin?.hotUpdate);
    const hotUpdate = typeof cssPlugin.hotUpdate === "function" ? cssPlugin.hotUpdate : cssPlugin.hotUpdate.handler;
    const context = { type: "update", file: cssFile, timestamp: Date.now(), modules: [], server };
    const sources = ["/* @block p-card */ .root--invalid {}", cssSource("large")];
    const results = await Promise.allSettled(sources.map((source) => hotUpdate.call(
      { warn() {} } as never,
      { ...context, read: async () => source } as never,
    )));
    assert.equal(results[0]?.status, "rejected");
    if (results[0]?.status === "rejected") assert.match(String(results[0].reason), /BEM003/);
    assert.equal(results[1]?.status, "fulfilled");
    const dts = await fs.readFile(`${cssFile}.d.ts`, "utf8");
    assert.match(dts, /readonly "rootLarge": string/);
    assert.doesNotMatch(dts, /rootCompact|rootInvalid/);

    await fs.writeFile(path.join(root, "Other.module.css"), cssSource("compact"), "utf8");
    const activeServer = server;
    await assert.rejects(() => activeServer.transformRequest("/Other.module.css"), /BEM003/);
  } finally {
    await closeServerAndRemoveRoot(server, root);
  }
});

test("Vite Adapterはimporter変更だけでProject stateを変更しない", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "bem-modules-dev-importer-"));
  const aFile = path.join(root, "A.module.css");
  const bFile = path.join(root, "B.module.css");
  const mainFile = path.join(root, "main.ts");
  let server: Awaited<ReturnType<typeof createServer>> | null = null;

  try {
    await fs.writeFile(aFile, "/* @block p-a */ .root {}", "utf8");
    await fs.writeFile(bFile, "/* @block p-b */ .root {}", "utf8");
    await fs.writeFile(mainFile, "import styles from './A.module.css';\nexport const value = styles.root;\n", "utf8");

    server = await createServer({
      root,
      configFile: false,
      logLevel: "silent",
      plugins: [bemModules({ types: false })],
      server: {
        middlewareMode: true,
        watch: null,
      },
    });

    await server.transformRequest("/main.ts");
    await server.transformRequest("/A.module.css");

    await fs.writeFile(mainFile, "import styles from './B.module.css';\nexport const value = styles.root;\n", "utf8");
    const plugins = server.config.plugins;
    const cssPlugin = plugins.find((plugin) => plugin.name === "vite-plugin-bem-modules:css");
    assert.ok(cssPlugin?.hotUpdate);
    const result = await (typeof cssPlugin.hotUpdate === "function" ? cssPlugin.hotUpdate : cssPlugin.hotUpdate.handler).call(
      { warn() {} } as never,
      {
        type: "update",
        file: mainFile,
        timestamp: Date.now(),
        modules: [],
        read: async () => await fs.readFile(mainFile, "utf8"),
        server,
      } as never,
    );
    assert.equal(result, undefined);
  } finally {
    await closeServerAndRemoveRoot(server, root);
  }
});
