import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { collectAdjacentDtsFiles, collectModuleFiles, isProjectFileInScope } from "../src/files.js";

test("走査除外はCSS Moduleと隣接d.tsへ同じ境界を適用する", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "bem-modules-files-"));
  try {
    const canonicalRoot = await fs.realpath(root);
    await fs.mkdir(path.join(root, "src"));
    await fs.mkdir(path.join(root, "src", "build"));
    await fs.mkdir(path.join(root, "fixtures"));
    await fs.mkdir(path.join(root, "build"));
    await fs.writeFile(path.join(root, "src", "Card.module.css"), ".root {}", "utf8");
    await fs.writeFile(path.join(root, "src", "Card.module.css.d.ts"), "// generated", "utf8");
    await fs.writeFile(path.join(root, "src", "build", "Source.module.css"), ".root {}", "utf8");
    await fs.writeFile(path.join(root, "build", "Output.module.css"), ".root {}", "utf8");
    await fs.writeFile(path.join(root, "fixtures", "Legacy.module.css"), ".root {}", "utf8");
    await fs.writeFile(path.join(root, "fixtures", "Legacy.module.css.d.ts"), "// generated", "utf8");

    assert.deepEqual(
      (await collectModuleFiles(root, { exclude: ["fixtures"] })).map((file) => path.relative(canonicalRoot, file)),
      [path.join("src", "Card.module.css"), path.join("src", "build", "Source.module.css")],
    );
    assert.deepEqual(
      (await collectAdjacentDtsFiles(root, { exclude: ["fixtures"] })).map((file) => path.relative(canonicalRoot, file)),
      [path.join("src", "Card.module.css.d.ts")],
    );
  } finally {
    await fs.rm(root, { recursive: true, force: true });
  }
});

test("file単位excludeはsourceと対応する隣接d.tsをscope外にする", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "bem-modules-files-file-exclude-"));
  try {
    const legacy = path.join(root, "Legacy.module.css");
    const current = path.join(root, "Current.module.css");
    await fs.writeFile(legacy, ".root {}", "utf8");
    await fs.writeFile(`${legacy}.d.ts`, "// Generated by vite-plugin-bem-modules. Do not edit.\n", "utf8");
    await fs.writeFile(current, ".root {}", "utf8");

    const scope = { exclude: ["Legacy.module.css"] };
    assert.deepEqual(
      (await collectModuleFiles(root, scope)).map((file) => path.basename(file)),
      ["Current.module.css"],
    );
    assert.deepEqual(
      (await collectAdjacentDtsFiles(root, scope)).map((file) => path.basename(file)),
      [],
    );
  } finally {
    await fs.rm(root, { recursive: true, force: true });
  }
});

test("走査と個別scope判定は既定の無視directoryと明示includeを同じように扱う", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "bem-modules-files-scope-"));
  try {
    const names = ["src/Card.module.css", "src/build/Source.module.css", "src/dist/Nested.module.css", "dist/Output.module.css", "build/Output.module.css"];
    for (const name of names) {
      const file = path.join(root, name);
      await fs.mkdir(path.dirname(file), { recursive: true });
      await fs.writeFile(file, ".root {}");
      await fs.writeFile(`${file}.d.ts`, "// generated\n");
    }
    const cases = [
      { scope: {}, expected: ["src/Card.module.css", "src/build/Source.module.css"] },
      { scope: { include: ["dist"] }, expected: ["dist/Output.module.css"] },
      { scope: { include: [".", "dist", "src/dist"] }, expected: ["dist/Output.module.css", "src/Card.module.css", "src/build/Source.module.css", "src/dist/Nested.module.css"] },
      { scope: { include: ["build/Output.module.css"] }, expected: ["build/Output.module.css"] },
      { scope: { include: ["dist"], exclude: ["dist/Output.module.css"] }, expected: [] },
    ];
    const canonicalRoot = await fs.realpath(root);
    const relative = (file: string) => path.relative(canonicalRoot, file).replaceAll("\\", "/");
    for (const { scope, expected } of cases) {
      assert.deepEqual((await collectModuleFiles(root, scope)).map(relative), expected);
      assert.deepEqual((await collectAdjacentDtsFiles(root, scope)).map(relative), expected.map((name) => `${name}.d.ts`));
      for (const name of names) {
        for (const suffix of ["", ".d.ts"]) {
          assert.equal(isProjectFileInScope(path.join(root, name + suffix), { root, ...scope }), expected.includes(name), `${JSON.stringify(scope)}: ${name}${suffix}`);
        }
      }
    }
  } finally {
    await fs.rm(root, { recursive: true, force: true });
  }
});
