import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import postcss from "postcss";
import { build } from "vite";
import bemModules, { createBemPostcssPlugin } from "../src/index.js";
import { KeyframesRegistry } from "../src/keyframes-registry.js";

async function withTempRoot<T>(callback: (root: string) => Promise<T>): Promise<T> {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "bem-modules-v02-"));
  try {
    return await callback(root);
  } finally {
    await fs.rm(root, { recursive: true, force: true });
  }
}

test("PostCSS factoryは管理対象のclass、ID、keyframes、animationを構文単位でglobal化する", async () => {
  await withTempRoot(async (root) => {
    const sourcePath = path.join(root, "Card.module.css");
    const result = await postcss([createBemPostcssPlugin({ types: true })]).process(`/* @block p-card */
.root { animation: 200ms ease fade; animation-name: slide, fade; }
.root--compact { color: red; }
:global(.utility) .child { display: block; }
#dialog { color: blue; }
@-webkit-keyframes fade { from { opacity: 0; } to { opacity: 1; } }
@keyframes slide { from { opacity: 0; } to { opacity: 1; } }
`, { from: sourcePath });

    assert.match(result.css, /:global\(\.p-card\)/);
    assert.match(result.css, /:global\(\.p-card--compact\)/);
    assert.match(result.css, /:global\(\.utility\) :global\(\.p-card__child\)/);
    assert.match(result.css, /:global\(#dialog\)/);
    assert.match(result.css, /@-webkit-keyframes :global\(fade\)/);
    assert.match(result.css, /animation: 200ms ease global\(fade\)/);
    assert.match(result.css, /animation-name: global\(slide\), global\(fade\)/);
    assert.match(result.css, /root: p-card/);
    assert.match(result.css, /rootCompact: p-card--compact/);
    assert.doesNotMatch(result.css, /utility: p-card/);

    const declaration = await fs.readFile(`${sourcePath}.d.ts`, "utf8");
    assert.match(declaration, /readonly "root": string;/);
    assert.match(declaration, /readonly "rootCompact": string;/);
    assert.match(declaration, /readonly "child": string;/);
    assert.doesNotMatch(declaration, /dialog|fade|slide|utility/);
  });
});

test("AtRule visitorが後から追加するclassは0.1.0の対応範囲外", async () => {
  await withTempRoot(async (root) => {
    const cssFile = path.join(root, "Card.module.css");
    await fs.writeFile(cssFile, "/* @block p-card */\n@generate-badge;\n.root { color: red; }\n");
    await fs.writeFile(path.join(root, "main.js"), "import styles from './Card.module.css'; export const rootClass = styles.root;\n");
    const addBadgeClass = {
      postcssPlugin: "test-add-badge-class",
      AtRule: {
        "generate-badge"(atRule: postcss.AtRule) {
          const rule = postcss.rule({ selector: ".badge", source: atRule.source });
          rule.append(postcss.decl({ prop: "color", value: "blue", source: atRule.source }));
          atRule.replaceWith(rule);
        },
      },
    };
    await build({
      root,
      configFile: false,
      logLevel: "silent",
      plugins: [
        ...bemModules({ types: true }),
        {
          name: "register-postcss-class-generator",
          config: () => ({ css: { postcss: { plugins: [addBadgeClass, createBemPostcssPlugin({ types: true })] } } }),
        },
      ],
      build: {
        outDir: "dist",
        emptyOutDir: true,
        lib: { entry: "main.js", formats: ["es"], fileName: "index" },
      },
    });
    const declaration = await fs.readFile(`${cssFile}.d.ts`, "utf8");
    assert.match(declaration, /readonly "root": string/);
    assert.doesNotMatch(declaration, /readonly "badge": string/);
  });
});

test("追加した :export 宣言は元の CSS ファイルを source に持つ", async () => {
  await withTempRoot(async (root) => {
    const sourcePath = path.join(root, "Card.module.css");
    const result = await postcss([createBemPostcssPlugin({ types: false })]).process(
      "/* @block p-card */\n.root { background: url(./icon.svg); }\n",
      { from: sourcePath },
    );
    const declarations: { prop: string; file: string | undefined }[] = [];
    result.root.walkDecls((declaration) => {
      declarations.push({ prop: declaration.prop, file: declaration.source?.input.file });
    });
    assert.ok(declarations.some(({ prop }) => prop === "root"));
    assert.deepEqual(declarations.map(({ file }) => file), declarations.map(() => sourcePath));
  });
});

test("無効化したPostCSS factoryはAST・台帳・excludedFiles・型へ副作用を与えない", async () => {
  await withTempRoot(async (root) => {
    const sourcePath = path.join(root, "Card.module.css");
    const dtsPath = `${sourcePath}.d.ts`;
    const source = `/* @block p-card */\n.root { animation: fade 1s linear; }\n@keyframes fade { from { opacity: 0; } to { opacity: 1; } }\n`;
    const existingDts = "// Generated by vite-plugin-bem-modules. Do not edit.\n// keep\n";
    await fs.writeFile(dtsPath, existingDts, "utf8");
    const registry = new KeyframesRegistry();
    const plugin = createBemPostcssPlugin({ types: true });
    const compilerOptions = {
      naming: { wordCase: "camel" as const, elementSeparator: "__" as const, modifierSeparator: "--" as const },
      globalScope: { exact: [], prefix: [] },
      modifierOutput: "only" as const,
    };

    plugin.configure({
      enabled: false,
      compilerOptions,
      dtsMode: "generate",
      keyframesRegistry: registry,
    });
    plugin.exclude(sourcePath);
    const disabled = await postcss([plugin]).process(source, { from: sourcePath });

    assert.equal(disabled.css, source);
    assert.deepEqual([...registry.fileToNames], []);
    assert.equal(await fs.readFile(dtsPath, "utf8"), existingDts);

    plugin.configure({
      enabled: true,
      compilerOptions,
      dtsMode: "ignore",
      keyframesRegistry: registry,
    });
    const enabled = await postcss([plugin]).process(source, { from: sourcePath });
    assert.match(enabled.css, /:global\(\.p-card\)/);
    assert.deepEqual([...registry.fileToNames.keys()].map((filePath) => path.basename(filePath)), ["Card.module.css"]);
  });
});

test("path風virtualのresolved IDは通常importと共有しても処理順に依存せず除外する", async () => {
  await withTempRoot(async (root) => {
    const sourcePath = path.join(root, "Generated.module.css");
    const virtualSpecifier = "virtual:shared-generated.module.css";
    const virtualId = sourcePath;
    const directSpecifier = "./Generated.module.css";
    await fs.writeFile(sourcePath, "/* @block p-card */\n.root { color: red; }\n", "utf8");

    const buildAndRead = async (imports: string) => {
      await fs.writeFile(
        path.join(root, "main.js"),
        `${imports} export const className = directStyles.root + virtualStyles.root;\n`,
        "utf8",
      );
      await build({
        root,
        configFile: false,
        logLevel: "silent",
        plugins: [
          {
            name: "shared-path-virtual-css-module",
            resolveId(id) {
              if (id === virtualSpecifier) return virtualId;
            },
            load(id) {
              if (id === virtualId) return fs.readFile(sourcePath, "utf8");
            },
          },
          ...bemModules({ types: false }),
          {
            name: "register-shared-path-virtual-bem-postcss",
            config: () => ({ css: { postcss: { plugins: [createBemPostcssPlugin({ types: false })] } } }),
          },
        ],
        build: {
          outDir: "dist",
          emptyOutDir: true,
          minify: false,
          lib: { entry: "main.js", formats: ["es"], fileName: "index" },
        },
      });
      const distFiles = await fs.readdir(path.join(root, "dist"));
      const cssFile = distFiles.find((file) => file.endsWith(".css"));
      assert.ok(cssFile);
      return fs.readFile(path.join(root, "dist", cssFile), "utf8");
    };

    const virtualFirst = await buildAndRead(
      `import virtualStyles from "${virtualSpecifier}"; import directStyles from "${directSpecifier}";\n`,
    );
    const normalFirst = await buildAndRead(
      `import directStyles from "${directSpecifier}"; import virtualStyles from "${virtualSpecifier}";\n`,
    );
    for (const css of [virtualFirst, normalFirst]) {
      assert.doesNotMatch(css, /\.p-card\s*\{/);
      assert.match(css, /_root_/);
    }
  });
});

test("css.modules:falseでは明示登録したBEM PostCSSもViteのCSS処理へ委譲する", async () => {
  await withTempRoot(async (root) => {
    const sourcePath = path.join(root, "Card.module.css");
    const source = `/* @block p-card */\n.root { animation: fade 1s linear; }\n#dialog { color: red; }\n@keyframes fade { from { opacity: 0; } to { opacity: 1; } }\n`;
    await fs.writeFile(sourcePath, source, "utf8");
    await fs.writeFile(path.join(root, "main.js"), "import './Card.module.css';\n", "utf8");

    const buildCss = async (plugins: Parameters<typeof build>[0]["plugins"]) => {
      await build({
        root,
        configFile: false,
        logLevel: "silent",
        plugins,
        css: { modules: false },
        build: { outDir: "dist", emptyOutDir: true, minify: false, lib: { entry: "main.js", formats: ["es"], fileName: "index" } },
      });
      const files = await fs.readdir(path.join(root, "dist"));
      const cssFile = files.find((file) => file.endsWith(".css"));
      assert.ok(cssFile);
      return fs.readFile(path.join(root, "dist", cssFile), "utf8");
    };

    const delegatedCss = await buildCss([]);
    const withCompanionCss = await buildCss([
      ...bemModules({ types: true }),
      {
        name: "register-bem-postcss-for-disabled-modules",
        config: () => ({ css: { postcss: { plugins: [createBemPostcssPlugin({ types: true })] } } }),
      },
    ]);

    assert.equal(withCompanionCss, delegatedCss);
    assert.match(withCompanionCss, /\.root\s*\{/);
    assert.match(withCompanionCss, /#dialog\s*\{/);
    assert.match(withCompanionCss, /@keyframes fade/);
    assert.match(withCompanionCss, /animation: fade/);
    assert.doesNotMatch(withCompanionCss, /:global\(|:export|global\(fade\)/);
    await assert.rejects(() => fs.access(`${sourcePath}.d.ts`), { code: "ENOENT" });

    const existingDts = "// Generated by vite-plugin-bem-modules. Do not edit.\n// keep\n";
    await fs.writeFile(`${sourcePath}.d.ts`, existingDts, "utf8");
    await buildCss([
      ...bemModules({ types: true }),
      {
        name: "register-bem-postcss-for-disabled-modules-again",
        config: () => ({ css: { postcss: { plugins: [createBemPostcssPlugin({ types: true })] } } }),
      },
    ]);
    assert.equal(await fs.readFile(`${sourcePath}.d.ts`, "utf8"), existingDts);
  });
});

test("PostCSS factoryは通常CSSの@blockを所有しない", async () => {
  await withTempRoot(async (root) => {
    const source = "/* @block p-global */ .root { color: red; }";
    const result = await postcss([createBemPostcssPlugin({ types: true })]).process(source, {
      from: path.join(root, "global.css"),
    });

    assert.equal(result.css, source);
    await assert.rejects(() => fs.access(path.join(root, "global.css.d.ts")), { code: "ENOENT" });
  });
});

test("PostCSS factoryのkeyframes台帳は再処理・改名・削除で古いfileを残さない", async () => {
  await withTempRoot(async (root) => {
    const fileA = path.join(root, "A.module.css");
    const fileB = path.join(root, "B.module.css");
    const plugin = createBemPostcssPlugin();
    const process = (from: string, body: string) => postcss([plugin]).process(
      `/* @block p-test */\n${body}`,
      { from },
    );

    await process(fileA, "@keyframes fade { from { opacity: 0; } to { opacity: 1; } }");
    const first = await process(fileB, "@keyframes fade { from { opacity: 0; } to { opacity: 1; } }");
    assert.equal(first.warnings().filter((warning) => /duplicate global keyframes/.test(warning.text)).length, 1);

    const resolved = await process(fileA, "@keyframes slide { from { opacity: 0; } to { opacity: 1; } }");
    assert.equal(resolved.warnings().filter((warning) => /duplicate global keyframes/.test(warning.text)).length, 0);

    const reintroduced = await process(fileA, "@keyframes fade { from { opacity: 0; } to { opacity: 1; } }");
    assert.equal(reintroduced.warnings().filter((warning) => /duplicate global keyframes/.test(warning.text)).length, 1);

    const unowned = await postcss([plugin]).process(".root {}", { from: fileA });
    assert.equal(unowned.warnings().filter((warning) => /duplicate global keyframes/.test(warning.text)).length, 0);
  });
});

test("Vite companionはBEM PostCSS pluginの明示登録がない起動を拒否する", async () => {
  await withTempRoot(async (root) => {
    await fs.writeFile(path.join(root, "main.js"), "import './Card.module.css';\n", "utf8");
    await fs.writeFile(path.join(root, "Card.module.css"), "/* @block p-card */\n.root {}\n", "utf8");

    await assert.rejects(
      build({
        root,
        configFile: false,
        logLevel: "silent",
        plugins: [bemModules({ types: false })],
        build: { outDir: "dist", emptyOutDir: true, write: false },
      }),
      /BEM010.*PostCSS plugin/i,
    );
  });
});

test("Vite companionはPostCSS plugin配列のnested wrapperを暗黙展開しない", async () => {
  await withTempRoot(async (root) => {
    await fs.writeFile(path.join(root, "main.js"), "import './Card.module.css';\n", "utf8");
    await fs.writeFile(path.join(root, "Card.module.css"), "/* @block p-card */\n.root {}\n", "utf8");

    await assert.rejects(
      build({
        root,
        configFile: false,
        logLevel: "silent",
        plugins: [bemModules({ types: false })],
        css: {
          postcss: {
            plugins: [[createBemPostcssPlugin()]] as never,
          },
        },
        build: { outDir: "dist", emptyOutDir: true, write: false },
      }),
      /BEM010.*PostCSS plugin/i,
    );
  });
});
