// Generated by vite-plugin-bem-modules. Do not edit.
export type Styles = {
  readonly "root": string;
  readonly "root--compact": string;
  readonly "rootCompact": string;
};

declare const styles: Styles;

export default styles;
