import fs from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { createBemDiagnosticError } from "./diagnostics.js";
import type { BemModuleSchema } from "./types.js";

export const GENERATED_DTS_HEADER = "// Generated by vite-plugin-bem-modules. Do not edit.\n";

function quote(value: string): string {
  return JSON.stringify(value);
}

function buildDts(schema: BemModuleSchema): string {
  const lines = [GENERATED_DTS_HEADER.trimEnd()];

  lines.push("export type Styles = {");

  for (const key of Object.keys(schema.classMap).sort()) {
    lines.push(`  readonly ${quote(key)}: string;`);
  }

  lines.push(
    "};",
    "",
    "declare const styles: Styles;",
    "",
    "export default styles;",
    "",
  );
  return lines.join("\n");
}

export function resolveDtsPath(filePath: string): string {
  return `${filePath}.d.ts`;
}

export function renderDts(schema: BemModuleSchema): string {
  return buildDts(schema);
}

function isMissingFileError(error: unknown): boolean {
  const code = (error as NodeJS.ErrnoException).code;
  return code === "ENOENT" || code === "ENOTDIR" || code === "EISDIR";
}

function unownedDtsError(filePath: string): Error {
  return createBemDiagnosticError(
    "BEM006",
    "the adjacent CSS Module declaration file is not owned by the plugin.",
    {
      file: filePath,
      details: [
        "only plugin-generated regular files can be replaced; move hand-written files or symbolic links before enabling generated declarations.",
      ],
    },
  );
}

export async function writeGeneratedDts(filePath: string, content: string): Promise<void> {
  let mode: number | undefined;
  try {
    const stats = await fs.lstat(filePath);
    if (!stats.isFile()) throw unownedDtsError(filePath);
    const existing = await fs.readFile(filePath, "utf8");
    if (!existing.startsWith(GENERATED_DTS_HEADER)) throw unownedDtsError(filePath);
    if (existing === content) return;
    mode = stats.mode;
  } catch (error) {
    if (!isMissingFileError(error)) throw error;
  }

  await fs.mkdir(path.dirname(filePath), { recursive: true });
  const temporary = path.join(path.dirname(filePath), `.bem-modules-${randomUUID()}.tmp`);
  const handle = await fs.open(temporary, "wx", mode);
  try {
    try {
      await handle.writeFile(content, "utf8");
    } finally {
      await handle.close();
    }
    await fs.rename(temporary, filePath);
  } finally {
    await fs.unlink(temporary).catch((error: unknown) => {
      if (!isMissingFileError(error)) throw error;
    });
  }
}

export async function removeGeneratedDts(filePath: string): Promise<void> {
  try {
    if (!(await fs.lstat(filePath)).isFile()) return;
    const existing = await fs.readFile(filePath, "utf8");
    if (!existing.startsWith(GENERATED_DTS_HEADER)) return;
    await fs.unlink(filePath);
  } catch (error) {
    if (!isMissingFileError(error)) throw error;
  }
}
