import type { BemModuleSchema } from "./types.js";

export const GENERATED_DTS_HEADER = "// Generated by vite-plugin-bem-modules. Do not edit.\n";

function quote(value: string): string {
  return JSON.stringify(value);
}

function buildDts(schema: BemModuleSchema): string {
  const lines = [GENERATED_DTS_HEADER.trimEnd()];

  lines.push("export type Styles = {");

  for (const key of Object.keys(schema.classMap).sort()) {
    lines.push(`  readonly ${quote(key)}: string;`);
  }

  lines.push(
    "};",
    "",
    "declare const styles: Styles;",
    "",
    "export default styles;",
    "",
  );
  return lines.join("\n");
}

export function resolveDtsPath(filePath: string): string {
  return `${filePath}.d.ts`;
}

export function renderDts(schema: BemModuleSchema): string {
  return buildDts(schema);
}
